//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include <cctype>
#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#include "absl/log/absl_log.h"
#include "absl/status/status.h"
#include "absl/strings/escaping.h"
#include "absl/strings/str_cat.h"
#include "absl/synchronization/mutex.h"
#include "frontend/collections/operation_manager.h"
#include "frontend/common/uris.h"
#include "frontend/converters/time.h"
#include "frontend/entities/instance.h"
#include "frontend/entities/instance_partition.h"
#include "frontend/persistence/backup_catalog.h"
#include "frontend/persistence/metadata_store.h"
#include "frontend/server/handler.h"
#include "google/longrunning/operations.pb.h"
#include "google/protobuf/empty.pb.h"
#include "google/spanner/admin/instance/v1/spanner_instance_admin.pb.h"
#include "googlesql/base/status_macros.h"

namespace database_api = ::google::spanner::admin::database::v1;
namespace instance_api = ::google::spanner::admin::instance::v1;
namespace operations_api = ::google::longrunning;
namespace protobuf_api = ::google::protobuf;

namespace google {
namespace spanner {
namespace emulator {
namespace frontend {
namespace {

constexpr int32_t kMaximumPageSize = 1000;

absl::Status ValidateConfigId(const std::string& id) {
  if (id.empty() || id.size() > 100) {
    return absl::InvalidArgumentError("Invalid instance config ID");
  }
  for (unsigned char ch : id) {
    if (!(std::isalnum(ch) || ch == '-' || ch == '_')) {
      return absl::InvalidArgumentError("Invalid instance config ID");
    }
  }
  return absl::OkStatus();
}


}  // namespace

absl::Status CreateInstanceConfig(
    RequestContext* ctx,
    const instance_api::CreateInstanceConfigRequest* request,
    operations_api::Operation* response) {
  absl::MutexLock admin_transaction_lock(
      &ctx->env()->admin_transaction_mutex());
  absl::string_view project_id;
  GOOGLESQL_RETURN_IF_ERROR(ParseProjectUri(request->parent(), &project_id));
  if (MakeProjectUri(project_id) != request->parent()) {
    return absl::InvalidArgumentError("Project name must be canonical");
  }
  GOOGLESQL_RETURN_IF_ERROR(ValidateConfigId(request->instance_config_id()));
  if (request->instance_config_id() == "emulator-config") {
    return absl::AlreadyExistsError(
        "The built-in emulator instance config is reserved");
  }
  if (!request->has_instance_config()) {
    return absl::InvalidArgumentError("Instance config must be provided");
  }
  instance_api::InstanceConfig config = request->instance_config();
  config.set_name(
      MakeInstanceConfigUri(project_id, request->instance_config_id()));
  GOOGLESQL_ASSIGN_OR_RETURN(
      std::shared_ptr<Operation> operation,
      ctx->env()->operation_manager()->CreateOperation(
          config.name(), OperationManager::kAutoGeneratedId));
  operation->SetResponse(config);
  operation->ToProto(response);

  MetadataStore* metadata = ctx->env()->metadata_store();
  bool config_created = false;
  bool metadata_persisted = false;
  auto rollback = [&](const absl::Status& failure) {
    absl::Status config_rollback = absl::OkStatus();
    if (config_created) {
      config_rollback = ctx->env()->DeleteInstanceConfig(config.name());
      if (metadata != nullptr) {
        metadata->RemovePendingOperation(response->name());
        metadata->RemoveInstanceConfig(config.name());
        if (metadata_persisted) {
          absl::Status metadata_rollback = metadata->Save();
          if (!metadata_rollback.ok()) config_rollback = metadata_rollback;
        }
      }
    }
    absl::Status operation_rollback =
        ctx->env()->operation_manager()->DeleteOperation(response->name());
    if (!config_rollback.ok() || !operation_rollback.ok()) {
      return absl::DataLossError(absl::StrCat(
          failure.message(), "; failed to roll back instance config creation",
          config_rollback.ok()
              ? ""
              : absl::StrCat("; config: ", config_rollback.message()),
          operation_rollback.ok()
              ? ""
              : absl::StrCat("; operation: ",
                             operation_rollback.message())));
    }
    return failure;
  };

  if (!request->validate_only()) {
    absl::Status create_status = ctx->env()->CreateInstanceConfig(config);
    if (!create_status.ok()) return rollback(create_status);
    config_created = true;
    if (metadata != nullptr) {
      metadata->SetInstanceConfig(
          config.name(), absl::Base64Escape(config.SerializeAsString()));
      metadata->SetPendingOperation(*response);
      absl::Status persistence_status = metadata->Save();
      if (!persistence_status.ok()) return rollback(persistence_status);
      metadata_persisted = true;
    }
  }

  absl::Status operation_status =
      ctx->env()->backup_catalog()->SaveOperation(*response);
  if (!operation_status.ok()) return rollback(operation_status);
  if (!request->validate_only() && metadata != nullptr) {
    metadata->RemovePendingOperation(response->name());
    absl::Status journal_status = metadata->Save();
    if (!journal_status.ok()) {
      ABSL_LOG(WARNING)
          << "Failed to clear promoted instance-config operation journal "
          << response->name() << ": " << journal_status;
    }
  }
  return absl::OkStatus();
}
REGISTER_GRPC_HANDLER(InstanceAdmin, CreateInstanceConfig);

absl::Status UpdateInstanceConfig(
    RequestContext* ctx,
    const instance_api::UpdateInstanceConfigRequest* request,
    operations_api::Operation* response) {
  absl::MutexLock admin_transaction_lock(
      &ctx->env()->admin_transaction_mutex());
  if (!request->has_instance_config() ||
      request->instance_config().name().empty()) {
    return absl::InvalidArgumentError("Instance config name must be provided");
  }
  absl::string_view project_id;
  absl::string_view config_id;
  GOOGLESQL_RETURN_IF_ERROR(ParseInstanceConfigUri(
      request->instance_config().name(), &project_id, &config_id));
  if (MakeInstanceConfigUri(project_id, config_id) !=
      request->instance_config().name()) {
    return absl::InvalidArgumentError(
        "Instance config name must be canonical");
  }
  GOOGLESQL_ASSIGN_OR_RETURN(
      instance_api::InstanceConfig current,
      ctx->env()->GetCustomInstanceConfig(request->instance_config().name()));
  const instance_api::InstanceConfig previous = current;
  if (request->update_mask().paths().empty()) {
    return absl::InvalidArgumentError(
        "Instance config update_mask must be provided");
  }
  for (const std::string& path : request->update_mask().paths()) {
    if (path == "display_name" || path == "displayName") {
      current.set_display_name(request->instance_config().display_name());
    } else if (path == "labels") {
      *current.mutable_labels() = request->instance_config().labels();
    } else {
      return absl::InvalidArgumentError(
          absl::StrCat("Unsupported instance config update field: ", path));
    }
  }
  GOOGLESQL_ASSIGN_OR_RETURN(
      std::shared_ptr<Operation> operation,
      ctx->env()->operation_manager()->CreateOperation(
          current.name(), OperationManager::kAutoGeneratedId));
  operation->SetResponse(current);
  operation->ToProto(response);

  MetadataStore* metadata = ctx->env()->metadata_store();
  bool config_updated = false;
  bool metadata_persisted = false;
  auto rollback = [&](const absl::Status& failure) {
    absl::Status config_rollback = absl::OkStatus();
    if (config_updated) {
      config_rollback = ctx->env()->UpdateInstanceConfig(previous);
      if (metadata != nullptr) {
        metadata->RemovePendingOperation(response->name());
        metadata->SetInstanceConfig(
            previous.name(), absl::Base64Escape(previous.SerializeAsString()));
        if (metadata_persisted) {
          absl::Status metadata_rollback = metadata->Save();
          if (!metadata_rollback.ok()) config_rollback = metadata_rollback;
        }
      }
    }
    absl::Status operation_rollback =
        ctx->env()->operation_manager()->DeleteOperation(response->name());
    if (!config_rollback.ok() || !operation_rollback.ok()) {
      return absl::DataLossError(absl::StrCat(
          failure.message(), "; failed to roll back instance config update",
          config_rollback.ok()
              ? ""
              : absl::StrCat("; config: ", config_rollback.message()),
          operation_rollback.ok()
              ? ""
              : absl::StrCat("; operation: ",
                             operation_rollback.message())));
    }
    return failure;
  };

  if (!request->validate_only()) {
    absl::Status update_status = ctx->env()->UpdateInstanceConfig(current);
    if (!update_status.ok()) return rollback(update_status);
    config_updated = true;
    if (metadata != nullptr) {
      metadata->SetInstanceConfig(
          current.name(), absl::Base64Escape(current.SerializeAsString()));
      metadata->SetPendingOperation(*response);
      absl::Status persistence_status = metadata->Save();
      if (!persistence_status.ok()) return rollback(persistence_status);
      metadata_persisted = true;
    }
  }

  absl::Status operation_status =
      ctx->env()->backup_catalog()->SaveOperation(*response);
  if (!operation_status.ok()) return rollback(operation_status);
  if (!request->validate_only() && metadata != nullptr) {
    metadata->RemovePendingOperation(response->name());
    absl::Status journal_status = metadata->Save();
    if (!journal_status.ok()) {
      ABSL_LOG(WARNING)
          << "Failed to clear promoted instance-config operation journal "
          << response->name() << ": " << journal_status;
    }
  }
  return absl::OkStatus();
}
REGISTER_GRPC_HANDLER(InstanceAdmin, UpdateInstanceConfig);

absl::Status DeleteInstanceConfig(
    RequestContext* ctx,
    const instance_api::DeleteInstanceConfigRequest* request,
    protobuf_api::Empty* response) {
  absl::MutexLock admin_transaction_lock(
      &ctx->env()->admin_transaction_mutex());
  absl::string_view project_id;
  absl::string_view config_id;
  GOOGLESQL_RETURN_IF_ERROR(
      ParseInstanceConfigUri(request->name(), &project_id, &config_id));
  if (MakeInstanceConfigUri(project_id, config_id) != request->name()) {
    return absl::InvalidArgumentError(
        "Instance config name must be canonical");
  }
  if (config_id == "emulator-config") {
    return absl::FailedPreconditionError(
        "The built-in emulator instance config cannot be deleted");
  }
  GOOGLESQL_ASSIGN_OR_RETURN(
      instance_api::InstanceConfig previous,
      ctx->env()->GetCustomInstanceConfig(request->name()));
  const std::string project_name = MakeProjectUri(project_id);
  GOOGLESQL_ASSIGN_OR_RETURN(
      std::vector<std::shared_ptr<Instance>> instances,
      ctx->env()->instance_manager()->ListInstances(project_name));
  for (const auto& instance : instances) {
    instance_api::Instance instance_proto;
    instance->ToProto(&instance_proto);
    if (instance_proto.config() == request->name()) {
      return absl::FailedPreconditionError(
          "Instance config is still used by an instance");
    }
    GOOGLESQL_ASSIGN_OR_RETURN(
        std::vector<std::shared_ptr<InstancePartition>> partitions,
        ctx->env()->instance_partition_manager()->ListInstancePartitions(
            instance_proto.name()));
    for (const auto& partition : partitions) {
      instance_api::InstancePartition partition_proto;
      partition->ToProto(&partition_proto);
      if (partition_proto.config() == request->name()) {
        return absl::FailedPreconditionError(
            "Instance config is still used by an instance partition");
      }
    }
  }
  for (const auto& backup : ctx->env()->backup_catalog()->AllBackups()) {
    if (backup.backup.state() == database_api::Backup::READY &&
        backup.source_instance_config == request->name()) {
      return absl::FailedPreconditionError(
          "Instance config is still referenced by a backup");
    }
  }
  if (request->validate_only()) {
    return absl::OkStatus();
  }
  MetadataStore* metadata = ctx->env()->metadata_store();
  std::optional<::google::iam::v1::Policy> previous_policy;
  if (metadata != nullptr) {
    previous_policy = metadata->GetIamPolicy(request->name());
    metadata->RemoveInstanceConfig(request->name());
    absl::Status status = metadata->Save();
    if (!status.ok()) {
      metadata->SetInstanceConfig(
          previous.name(), absl::Base64Escape(previous.SerializeAsString()));
      if (previous_policy.has_value()) {
        metadata->SetIamPolicy(request->name(), *previous_policy);
      }
      return status;
    }
  }
  absl::Status delete_status =
      ctx->env()->DeleteInstanceConfig(request->name());
  if (!delete_status.ok()) {
    if (metadata != nullptr) {
      metadata->SetInstanceConfig(
          previous.name(), absl::Base64Escape(previous.SerializeAsString()));
      if (previous_policy.has_value()) {
        metadata->SetIamPolicy(request->name(), *previous_policy);
      }
      absl::Status rollback_status = metadata->Save();
      if (!rollback_status.ok()) {
        return absl::DataLossError(absl::StrCat(
            delete_status.message(),
            "; failed to restore instance config metadata: ",
            rollback_status.message()));
      }
    }
    return delete_status;
  }
  ctx->env()->RemoveIamPolicy(request->name());
  return absl::OkStatus();
}
REGISTER_GRPC_HANDLER(InstanceAdmin, DeleteInstanceConfig);

absl::Status ListInstanceConfigOperations(
    RequestContext* ctx,
    const instance_api::ListInstanceConfigOperationsRequest* request,
    instance_api::ListInstanceConfigOperationsResponse* response) {
  absl::string_view project_id;
  GOOGLESQL_RETURN_IF_ERROR(ParseProjectUri(request->parent(), &project_id));
  if (MakeProjectUri(project_id) != request->parent()) {
    return absl::InvalidArgumentError("Project name must be canonical");
  }
  GOOGLESQL_ASSIGN_OR_RETURN(
      std::vector<std::shared_ptr<Operation>> operations,
      ctx->env()->operation_manager()->ListOperations(
          absl::StrCat(request->parent(), "/")));
  int32_t page_size = request->page_size();
  if (page_size <= 0 || page_size > kMaximumPageSize) {
    page_size = kMaximumPageSize;
  }
  for (const auto& operation : operations) {
    operations_api::Operation proto;
    operation->ToProto(&proto);
    absl::string_view operation_id;
    OperationResourceType resource_type;
    GOOGLESQL_RETURN_IF_ERROR(ParseOperationUri(
        proto.name(), /*resource_uri=*/nullptr, &operation_id,
        &resource_type));
    if (resource_type != OperationResourceType::kInstanceConfig) continue;
    if (!request->page_token().empty() &&
        proto.name() < request->page_token()) {
      continue;
    }
    if (response->operations_size() >= page_size) {
      response->set_next_page_token(proto.name());
      break;
    }
    *response->add_operations() = std::move(proto);
  }
  return absl::OkStatus();
}
REGISTER_GRPC_HANDLER(InstanceAdmin, ListInstanceConfigOperations);

absl::Status MoveInstance(RequestContext* ctx,
                          const instance_api::MoveInstanceRequest* request,
                          operations_api::Operation* response) {
  absl::MutexLock admin_transaction_lock(
      &ctx->env()->admin_transaction_mutex());
  if (request->name().empty() || request->target_config().empty()) {
    return absl::InvalidArgumentError(
        "Instance name and target_config must be provided");
  }
  absl::string_view project_id;
  absl::string_view instance_id;
  GOOGLESQL_RETURN_IF_ERROR(
      ParseInstanceUri(request->name(), &project_id, &instance_id));
  if (MakeInstanceUri(project_id, instance_id) != request->name()) {
    return absl::InvalidArgumentError("Instance name must be canonical");
  }
  absl::string_view config_project;
  absl::string_view config_id;
  GOOGLESQL_RETURN_IF_ERROR(ParseInstanceConfigUri(
      request->target_config(), &config_project, &config_id));
  if (MakeInstanceConfigUri(config_project, config_id) !=
      request->target_config()) {
    return absl::InvalidArgumentError(
        "Instance target_config must be canonical");
  }
  if (config_project != project_id) {
    return absl::InvalidArgumentError(
        "Instance and target_config must belong to the same project");
  }
  if (config_id != "emulator-config") {
    GOOGLESQL_RETURN_IF_ERROR(
        ctx->env()->GetCustomInstanceConfig(request->target_config()).status());
  }
  GOOGLESQL_ASSIGN_OR_RETURN(
      std::shared_ptr<Instance> instance,
      ctx->env()->instance_manager()->GetInstance(request->name()));
  instance_api::Instance previous_instance;
  instance->ToProto(&previous_instance);
  GOOGLESQL_ASSIGN_OR_RETURN(
      absl::Time previous_update_time,
      TimestampFromProto(previous_instance.update_time()));
  GOOGLESQL_ASSIGN_OR_RETURN(
      std::shared_ptr<Operation> operation,
      ctx->env()->operation_manager()->CreateOperation(
          request->name(), OperationManager::kAutoGeneratedId));

  const absl::Time update_time = ctx->env()->clock()->Now();
  instance->UpdateConfig(request->target_config(), update_time);
  instance_api::Instance instance_proto;
  instance->ToProto(&instance_proto);
  operation->SetResponse(instance_proto);
  operation->ToProto(response);

  MetadataStore* metadata = ctx->env()->metadata_store();
  bool metadata_persisted = false;
  auto rollback = [&](const absl::Status& failure) {
    instance->UpdateConfig(previous_instance.config(), previous_update_time);
    absl::Status metadata_rollback = absl::OkStatus();
    if (metadata != nullptr) {
      metadata->RemovePendingOperation(response->name());
      metadata->UpdateInstance(
          previous_instance.name(), previous_instance.config(),
          previous_instance.display_name(), previous_instance.processing_units(),
          std::map<std::string, std::string>(
              previous_instance.labels().begin(),
              previous_instance.labels().end()),
          absl::FormatTime(absl::RFC3339_full, previous_update_time,
                           absl::UTCTimeZone()));
      metadata->UpdateInstanceNodeCount(previous_instance.name(),
                                        previous_instance.node_count());
      if (metadata_persisted) {
        metadata_rollback = metadata->Save();
      }
    }
    absl::Status operation_rollback =
        ctx->env()->operation_manager()->DeleteOperation(response->name());
    if (!metadata_rollback.ok() || !operation_rollback.ok()) {
      return absl::DataLossError(absl::StrCat(
          failure.message(), "; failed to roll back instance move",
          metadata_rollback.ok()
              ? ""
              : absl::StrCat("; metadata: ", metadata_rollback.message()),
          operation_rollback.ok()
              ? ""
              : absl::StrCat("; operation: ",
                             operation_rollback.message())));
    }
    return failure;
  };

  if (metadata != nullptr) {
    metadata->UpdateInstance(
        instance_proto.name(), instance_proto.config(),
        instance_proto.display_name(), instance_proto.processing_units(),
        std::map<std::string, std::string>(instance_proto.labels().begin(),
                                           instance_proto.labels().end()),
        absl::FormatTime(absl::RFC3339_full, update_time,
                         absl::UTCTimeZone()));
    metadata->SetPendingOperation(*response);
    metadata->UpdateInstanceNodeCount(instance_proto.name(),
                                      instance_proto.node_count());
    absl::Status save_status = metadata->Save();
    if (!save_status.ok()) return rollback(save_status);
    metadata_persisted = true;
  }
  absl::Status operation_status =
      ctx->env()->backup_catalog()->SaveOperation(*response);
  if (!operation_status.ok()) return rollback(operation_status);
  if (metadata != nullptr) {
    metadata->RemovePendingOperation(response->name());
    absl::Status journal_status = metadata->Save();
    if (!journal_status.ok()) {
      ABSL_LOG(WARNING)
          << "Failed to clear promoted move-instance operation journal "
          << response->name() << ": " << journal_status;
    }
  }
  return absl::OkStatus();
}
REGISTER_GRPC_HANDLER(InstanceAdmin, MoveInstance);

}  // namespace frontend
}  // namespace emulator
}  // namespace spanner
}  // namespace google
