//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "backend/query/search/score_ngrams_evaluator.h"

#include <string>
#include <vector>

#include "googlesql/public/value.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "googlesql/base/testing/status_matchers.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "backend/query/search/plain_full_text_tokenizer.h"
#include "backend/query/search/ngrams_tokenizer.h"
#include "backend/query/search/tokenizer.h"

namespace google {
namespace spanner {
namespace emulator {
namespace backend {
namespace query {
namespace search {

using testing::HasSubstr;
using googlesql_base::testing::StatusIs;

TEST(ScoreNgramsEvaluatorTest, EvaluateWrongSearchColumnType) {
  std::vector<googlesql::Value> args;
  args.push_back(googlesql::Value::Bool(false));
  args.push_back(googlesql::Value::String("test"));

  EXPECT_THAT(
      ScoreNgramsEvaluator::Evaluate(args),
      StatusIs(
          absl::StatusCode::kInvalidArgument,
          HasSubstr("Invalid search query. Trying to execute search related "
                    "function on unsupported column type: BOOL.")));
}

TEST(ScoreNgramsEvaluatorTest, EvaluateWrongSearchQueryType) {
  std::vector<googlesql::Value> args;
  const auto ngrams_tokenlist =
      NgramsTokenizer::Tokenize({googlesql::Value::String("foo")});
  args.push_back(*ngrams_tokenlist);
  args.push_back(googlesql::Value::Bool(false));

  EXPECT_THAT(ScoreNgramsEvaluator::Evaluate(args),
              StatusIs(absl::StatusCode::kInvalidArgument,
                       HasSubstr("Invalid search query type: BOOL.")));
}

TEST(ScoreNgramsEvaluatorTest, EvaluateOnWrongTokenList) {
  std::vector<googlesql::Value> args;
  const auto fulltext_tokenlist =
      PlainFullTextTokenizer::Tokenize({googlesql::Value::String("fulltext")});
  args.push_back(*fulltext_tokenlist);
  args.push_back(googlesql::Value::String("test"));

  EXPECT_THAT(
      ScoreNgramsEvaluator::Evaluate(args),
      StatusIs(
          absl::StatusCode::kInvalidArgument,
          HasSubstr(
              "SCORE_NGRAMS function's first argument must be a TOKENLIST "
              "column generated by TOKENIZE_SUBSTRING or TOKENIZE_NGRAMS")));
}

TEST(ScoreNgramsEvaluatorTest, EvaluateOnNullQueryReturnsZero) {
  std::vector<googlesql::Value> args;
  const auto ngrams_tokenlist =
      NgramsTokenizer::Tokenize({googlesql::Value::String("foo")});
  args.push_back(*ngrams_tokenlist);
  args.push_back(googlesql::Value::NullString());

  absl::StatusOr<googlesql::Value> result =
      ScoreNgramsEvaluator::Evaluate(args);
  GOOGLESQL_EXPECT_OK(result.status());

  googlesql::Value score = result.value();
  EXPECT_TRUE(score.type()->IsDouble());
  EXPECT_EQ(0.0, score.double_value());
}

TEST(ScoreNgramsEvaluatorTest, EvaluateOnNullTokenListReturnsZero) {
  std::vector<googlesql::Value> args;
  args.push_back(googlesql::Value::NullTokenList());
  args.push_back(googlesql::Value::String("test"));

  absl::StatusOr<googlesql::Value> result =
      ScoreNgramsEvaluator::Evaluate(args);
  GOOGLESQL_EXPECT_OK(result.status());

  googlesql::Value score = result.value();
  EXPECT_TRUE(score.type()->IsDouble());
  EXPECT_EQ(0.0, score.double_value());
}

TEST(ScoreNgramsEvaluatorTest, OnlyTrigramsAlgorithmIsAccepted) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto tokens, NgramsTokenizer::Tokenize({googlesql::Value::String("span")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto default_score,
      ScoreNgramsEvaluator::Evaluate({tokens, googlesql::Value::String("span")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto trigrams_score,
      ScoreNgramsEvaluator::Evaluate(
          {tokens, googlesql::Value::String("span"),
           googlesql::Value::String("trigrams")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto null_algorithm_score,
      ScoreNgramsEvaluator::Evaluate(
          {tokens, googlesql::Value::String("span"),
           googlesql::Value::NullString()}));
  EXPECT_EQ(default_score.double_value(), trigrams_score.double_value());
  EXPECT_EQ(default_score.double_value(), null_algorithm_score.double_value());
  EXPECT_THAT(ScoreNgramsEvaluator::Evaluate(
                  {tokens, googlesql::Value::String("span"),
                   googlesql::Value::String("bigrams")}),
              StatusIs(absl::StatusCode::kInvalidArgument,
                       HasSubstr("SCORE_NGRAMS algorithm")));
}

TEST(ScoreNgramsEvaluatorTest, EmptyTrigramSetsScoreZero) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto tokens, NgramsTokenizer::Tokenize({googlesql::Value::String("")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto score,
      ScoreNgramsEvaluator::Evaluate({tokens, googlesql::Value::String("")}));
  EXPECT_EQ(0.0, score.double_value());
}

TEST(ScoreNgramsEvaluatorTest, ArrayAggregatorScoresArrayElements) {
  const googlesql::Value array_tokens = TokenListFromStrings(
      {"substring-3-3-0", "span", kGapString, "cloud", kGapString});
  auto score = [](const googlesql::Value& tokens,
                  googlesql::Value array_aggregator) {
    return ScoreNgramsEvaluator::Evaluate(
        {tokens, googlesql::Value::String("span"),
         googlesql::Value::NullString(), googlesql::Value::NullString(),
         array_aggregator});
  };

  // Flattening scores the trigrams of all elements together: 2 of the 5
  // source trigrams match the 2 query trigrams.
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(auto flatten,
                       score(array_tokens, googlesql::Value::String("flatten")));
  EXPECT_DOUBLE_EQ(flatten.double_value(), 0.4);
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(auto by_default,
                       score(array_tokens, googlesql::Value::NullString()));
  EXPECT_DOUBLE_EQ(by_default.double_value(), 0.4);

  // max_element scores the best element, which matches the query exactly.
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto max_element,
      score(array_tokens, googlesql::Value::String("max_element")));
  EXPECT_DOUBLE_EQ(max_element.double_value(), 1.0);

  EXPECT_THAT(score(array_tokens, googlesql::Value::String("sum")),
              StatusIs(absl::StatusCode::kInvalidArgument,
                       HasSubstr("array_aggregator")));
  EXPECT_THAT(score(TokenListFromStrings({"substring-3-3-0", "span"}),
                    googlesql::Value::String("max_element")),
              StatusIs(absl::StatusCode::kInvalidArgument,
                       HasSubstr("array column")));

  // An empty array has no elements to score.
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto empty_array,
      score(TokenListFromStrings({"substring-3-3-0"}),
            googlesql::Value::String("max_element")));
  EXPECT_EQ(empty_array.double_value(), 0.0);
}

struct ScoreNgramsEvaluatorTestCase {
  std::vector<std::string> tokens;
  std::string query;
  double expected_result;
};

using ScoreNgramsEvaluatorTest =
    ::testing::TestWithParam<ScoreNgramsEvaluatorTestCase>;

TEST_P(ScoreNgramsEvaluatorTest, TestScoreNgramsEvaluate) {
  const ScoreNgramsEvaluatorTestCase& test_case = GetParam();
  googlesql::Value query = googlesql::Value::String(test_case.query);
  std::vector<googlesql::Value> args{TokenListFromStrings(test_case.tokens),
                                     query};

  absl::StatusOr<googlesql::Value> result =
      ScoreNgramsEvaluator::Evaluate(args);
  GOOGLESQL_EXPECT_OK(result.status());

  googlesql::Value score = result.value();
  EXPECT_TRUE(score.type()->IsDouble());

  EXPECT_EQ(test_case.expected_result, score.double_value());
};

INSTANTIATE_TEST_SUITE_P(
    ScoreNgramsEvaluatorTestSuite, ScoreNgramsEvaluatorTest,
    testing::ValuesIn<ScoreNgramsEvaluatorTestCase>({
        {{"ngrams-3-3-0", "spa", "pan"}, "span", 1},
        {{"ngrams-3-3-0", "spa", "pan"}, "spaz", 0.33333333333333331},
        {{"substring-3-3-0", "foo", "bar"}, "foo+bar=baz", 0.22222222222222221},
        // Test cases for concatenated tokenlists
        {{"ngrams-3-3-0", "spa", "pan", kGapString, "ngrams-3-3-0", "clo",
          "lou", "oud"},
         "spancloud",
         0.7142857142857143},
        {{"ngrams-3-3-0", "spa", "pan", kGapString, "ngrams-3-3-0", "clo",
          "lou", "oud"},
         "spnaclodu",
         0.090909090909090912},
        {{"ngrams-3-3-0", "spa", "pan", kGapString, "substring-3-3-0", "foo",
          "bar"},
         "spaz;foo+bar=baz",
         0.2},
    }));

}  // namespace search
}  // namespace query
}  // namespace backend
}  // namespace emulator
}  // namespace spanner
}  // namespace google
