//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "backend/query/search/score_evaluator.h"

#include <optional>
#include <string>
#include <utility>
#include <vector>

#include "googlesql/public/json_value.h"
#include "googlesql/public/value.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "googlesql/base/testing/status_matchers.h"
#include "absl/status/statusor.h"
#include "absl/strings/str_split.h"
#include "backend/query/search/exact_match_tokenizer.h"
#include "backend/query/search/plain_full_text_tokenizer.h"
#include "backend/query/search/tokenizer.h"

namespace google {
namespace spanner {
namespace emulator {
namespace backend {
namespace query {
namespace search {

using testing::HasSubstr;
using googlesql_base::testing::IsOkAndHolds;
using googlesql_base::testing::StatusIs;

TEST(ScoreEvaluatorTest, EvaluateWrongSearchColumnType) {
  std::vector<googlesql::Value> args;
  args.push_back(googlesql::Value::Bool(false));
  args.push_back(googlesql::Value::String("test"));

  EXPECT_THAT(
      ScoreEvaluator::Evaluate(args),
      StatusIs(
          absl::StatusCode::kInvalidArgument,
          HasSubstr("Invalid search query. Trying to execute search related "
                    "function on unsupported column type: BOOL.")));
}

TEST(ScoreEvaluatorTest, EvaluateWrongSearchQueryType) {
  std::vector<googlesql::Value> args;
  args.push_back(googlesql::Value::NullTokenList());
  args.push_back(googlesql::Value::Bool(false));

  EXPECT_THAT(ScoreEvaluator::Evaluate(args),
              StatusIs(absl::StatusCode::kInvalidArgument,
                       HasSubstr("Invalid search query type: BOOL.")));
}

TEST(ScoreEvaluatorTest, EvaluateOnWrongTokenList) {
  std::vector<googlesql::Value> args;
  const auto fulltext_tokenlist =
      ExactMatchTokenizer::Tokenize({googlesql::Value::String("numeric")});
  args.push_back(*fulltext_tokenlist);
  args.push_back(googlesql::Value::String("test"));

  EXPECT_THAT(
      ScoreEvaluator::Evaluate(args),
      StatusIs(absl::StatusCode::kInvalidArgument,
               HasSubstr("SCORE function's first argument must be a TOKENLIST "
                         "column generated by TOKENIZE_FULLTEXT")));
}

TEST(ScoreEvaluatorTest, TokenCategoryChangesRanking) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto small,
      PlainFullTextTokenizer::Tokenize({googlesql::Value::String("apple")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto title,
      PlainFullTextTokenizer::Tokenize(
          {googlesql::Value::String("apple"), googlesql::Value::NullString(),
           googlesql::Value::NullString(), googlesql::Value::String("title")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto small_score,
      ScoreEvaluator::Evaluate({small, googlesql::Value::String("apple")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto title_score,
      ScoreEvaluator::Evaluate({title, googlesql::Value::String("apple")}));
  EXPECT_GT(title_score.double_value(), small_score.double_value());
}

TEST(ScoreEvaluatorTest, ScoreOptionsAreNotSilentlyIgnored) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto tokens,
      PlainFullTextTokenizer::Tokenize({googlesql::Value::String("apple")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto empty_options, googlesql::JSONValue::ParseJSONString("{}"));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto default_score,
      ScoreEvaluator::Evaluate({tokens, googlesql::Value::String("apple")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto null_options_score,
      ScoreEvaluator::Evaluate({tokens, googlesql::Value::String("apple"),
                                googlesql::Value::NullBool(),
                                googlesql::Value::NullString(),
                                googlesql::Value::NullString(),
                                googlesql::Value::NullJson()}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto empty_options_score,
      ScoreEvaluator::Evaluate({tokens, googlesql::Value::String("apple"),
                                googlesql::Value::NullBool(),
                                googlesql::Value::NullString(),
                                googlesql::Value::NullString(),
                                googlesql::Value::Json(std::move(empty_options))}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto unparsed_empty_options_score,
      ScoreEvaluator::Evaluate(
          {tokens, googlesql::Value::String("apple"),
           googlesql::Value::NullBool(), googlesql::Value::NullString(),
           googlesql::Value::NullString(),
           googlesql::Value::UnvalidatedJsonString("{}")}));
  EXPECT_EQ(null_options_score.double_value(), default_score.double_value());
  EXPECT_EQ(empty_options_score.double_value(), default_score.double_value());
  EXPECT_EQ(unparsed_empty_options_score.double_value(),
            default_score.double_value());

  for (const char* unsupported_options :
       {R"({"bigram_weight":3})", R"({"idf_weight":0.5})"}) {
    EXPECT_THAT(
        ScoreEvaluator::Evaluate(
            {tokens, googlesql::Value::String("apple"),
             googlesql::Value::NullBool(), googlesql::Value::NullString(),
             googlesql::Value::NullString(),
             googlesql::Value::UnvalidatedJsonString(unsupported_options)}),
        StatusIs(absl::StatusCode::kUnimplemented, HasSubstr("SCORE option")))
        << unsupported_options;
  }
  for (const char* invalid_options :
       {R"({"unknown":1})", R"({"version":3})", R"({"version":"1"})",
        R"({"token_category_weights":{"huge":2}})",
        R"({"token_category_weights":{"title":-1}})",
        R"({"token_category_weights":[1]})"}) {
    EXPECT_THAT(
        ScoreEvaluator::Evaluate(
            {tokens, googlesql::Value::String("apple"),
             googlesql::Value::NullBool(), googlesql::Value::NullString(),
             googlesql::Value::NullString(),
             googlesql::Value::UnvalidatedJsonString(invalid_options)}),
        StatusIs(absl::StatusCode::kInvalidArgument, HasSubstr("SCORE")))
        << invalid_options;
  }

  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto array_options, googlesql::JSONValue::ParseJSONString("[]"));
  EXPECT_THAT(
      ScoreEvaluator::Evaluate({tokens, googlesql::Value::String("apple"),
                                googlesql::Value::NullBool(),
                                googlesql::Value::NullString(),
                                googlesql::Value::NullString(),
                                googlesql::Value::Json(std::move(array_options))}),
      StatusIs(absl::StatusCode::kInvalidArgument,
               HasSubstr("SCORE options")));
  EXPECT_FALSE(ScoreEvaluator::Evaluate(
                   {tokens, googlesql::Value::String("apple"),
                    googlesql::Value::NullBool(),
                    googlesql::Value::NullString(),
                    googlesql::Value::NullString(),
                    googlesql::Value::UnvalidatedJsonString("{")})
                   .ok());
}

TEST(ScoreEvaluatorTest, VersionOptionKeepsTheLocalScore) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto tokens,
      PlainFullTextTokenizer::Tokenize({googlesql::Value::String("apple")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto default_score,
      ScoreEvaluator::Evaluate({tokens, googlesql::Value::String("apple")}));
  for (const char* options : {R"({"version":1})", R"({"version":2})"}) {
    GOOGLESQL_ASSERT_OK_AND_ASSIGN(
        auto score,
        ScoreEvaluator::Evaluate(
            {tokens, googlesql::Value::String("apple"),
             googlesql::Value::NullBool(), googlesql::Value::NullString(),
             googlesql::Value::NullString(),
             googlesql::Value::UnvalidatedJsonString(options)}));
    EXPECT_EQ(score.double_value(), default_score.double_value()) << options;
  }
}

TEST(ScoreEvaluatorTest, TokenCategoryWeightsScaleHits) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto title,
      PlainFullTextTokenizer::Tokenize(
          {googlesql::Value::String("apple"), googlesql::Value::NullString(),
           googlesql::Value::NullString(), googlesql::Value::String("title")}));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      auto small,
      PlainFullTextTokenizer::Tokenize({googlesql::Value::String("apple")}));
  auto score = [](const googlesql::Value& tokens,
                  const char* options) -> absl::StatusOr<double> {
    GOOGLESQL_ASSIGN_OR_RETURN(
        googlesql::Value value,
        ScoreEvaluator::Evaluate(
            {tokens, googlesql::Value::String("apple"),
             googlesql::Value::NullBool(), googlesql::Value::NullString(),
             googlesql::Value::NullString(),
             googlesql::Value::UnvalidatedJsonString(options)}));
    return value.double_value();
  };
  // A title hit scores 1 + 3, a small hit 1.
  EXPECT_THAT(score(title, "{}"), IsOkAndHolds(4.0));
  EXPECT_THAT(score(small, "{}"), IsOkAndHolds(1.0));
  EXPECT_THAT(score(title, R"({"token_category_weights":{"title":0.5}})"),
              IsOkAndHolds(2.0));
  EXPECT_THAT(score(small, R"({"token_category_weights":{"small":3}})"),
              IsOkAndHolds(3.0));
  // The weight of another category doesn't change the score.
  EXPECT_THAT(score(title, R"({"token_category_weights":{"small":0}})"),
              IsOkAndHolds(4.0));
}

struct ScoreEvaluatorTestCase {
  std::string original_doc;
  std::string query;
  std::optional<std::string> dialect;
  double expected_result;
};

using ScoreEvaluatorTest = ::testing::TestWithParam<ScoreEvaluatorTestCase>;

TEST_P(ScoreEvaluatorTest, TestEvaluation) {
  const ScoreEvaluatorTestCase& test_case = GetParam();

  // Construct full text tokenized TokenList.
  std::vector<std::string> tokens =
      absl::StrSplit(test_case.original_doc, ", ");
  tokens.insert(tokens.begin(), "fulltext-0");
  googlesql::Value tokenlist = TokenListFromStrings(tokens);

  std::vector<googlesql::Value> args;
  args.push_back(tokenlist);
  args.push_back(googlesql::Value::String(test_case.query));
  args.push_back(googlesql::Value::NullBool());    // enhance_query
  args.push_back(googlesql::Value::NullString());  // language_tag
  if (!test_case.dialect.has_value()) {
    args.push_back(googlesql::Value::NullString());
  } else {
    args.push_back(googlesql::Value::String(*test_case.dialect));
  }

  absl::StatusOr<googlesql::Value> result = ScoreEvaluator::Evaluate(args);
  GOOGLESQL_EXPECT_OK(result.status());

  googlesql::Value score = result.value();
  EXPECT_TRUE(score.type()->IsDouble());

  EXPECT_EQ(test_case.expected_result, score.double_value());
}

INSTANTIATE_TEST_SUITE_P(
    DefaultDialectBasicTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"", "foo", std::nullopt, 0.0},
        {"foo", "", std::nullopt, 0.0},
        {"foo", "foo", std::nullopt, 1.0},
        {"foo, foo, bar, foo, baz, foo, blah", "foo", std::nullopt, 4.0},
        {"foo, foo, bar, foo, baz, foo, blah", "foo bar", std::nullopt, 5.0},
        {"foo, foo, bar, foo, baz, foo, blah", "baz | blah", std::nullopt, 2.0},
    }));

INSTANTIATE_TEST_SUITE_P(
    DefaultDialectCaseInsensitivityTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"foo, foo, bar, foo, baz, foo, blah", "FOO", std::nullopt, 4.0},
        {"foo, foo, bar, foo, baz, foo, blah", "FOO BAR", std::nullopt, 5.0},
    }));

INSTANTIATE_TEST_SUITE_P(
    WordsDialectBasicTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"foo", "", "words", 0.0},
        {"foo", "##", "words", 0.0},
        {"foo, foo, bar, foo, baz, foo, blah", "foo", "words", 4.0},
        {"foo, foo, bar, foo, baz, foo, blah", "foo bar", "WORDS", 5.0},
        {"foo, foo, bar, foo, baz, foo, blah", "baz | blah", "WoRdS", 2.0},
    }));

INSTANTIATE_TEST_SUITE_P(
    WordsDialectCaseInsensitivityTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"foo, foo, bar, foo, baz, foo, blah", "FOO", "words", 4.0},
        {"foo, foo, bar, foo, baz, foo, blah", "FOO BAR", "words", 5.0},
    }));

INSTANTIATE_TEST_SUITE_P(
    WordsPhraseDialectBasicTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"foo", "", "words_phrase", 0.0},
        {"foo", "##", "words_phrase", 0.0},
        {"foo, foo, bar, foo, baz, foo, blah", "foo bar", "words_phrase", 1.0},
        {"foo, foo, bar, foo, baz, foo, blah", "foo foo", "WORDS_PHRASE", 1.0},
        {"foo, foo, bar, foo, baz, foo, blah", "foo baz", "Words_Phrase", 1.0},
        {"foo, foo, bar, foo, baz, foo, blah", "foo other", "words_phrase",
         0.0},
        {"foo, foo, foo", "foo foo", "words_phrase", 2.0},
        {"foo, foo, foo, foo", "foo foo", "words_phrase", 3.0},
    }));

INSTANTIATE_TEST_SUITE_P(
    WordsPhraseDialectCaseInsensitivityTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"foo, foo, bar, foo, baz, foo, blah", "FOO BAR", "words_phrase", 1.0},
        {"foo, foo, bar, foo, baz, foo, blah", "FOO FOO", "words_phrase", 1.0},
    }));

INSTANTIATE_TEST_SUITE_P(
    WordsPhraseDialectNoSubstringMatchingTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"cloud emulator", "cloud emu", "words_phrase", 0.0},
        {"cloud emulator", "emu", "words_phrase", 0.0},
    }));

INSTANTIATE_TEST_SUITE_P(
    RQueryDialectBasicTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"foo, foo, bar, foo, baz, foo, blah", "foo bar", "rquery", 5.0},
        {"foo, foo, bar, foo, baz, foo, blah", "baz | blah", "RQUERY", 2.0},
    }));

INSTANTIATE_TEST_SUITE_P(
    RQueryDialectCaseInsensitivityTests, ScoreEvaluatorTest,
    testing::ValuesIn<ScoreEvaluatorTestCase>({
        {"foo, foo, bar, foo, baz, foo, blah", "FOO BAR", "rquery", 5.0},
    }));

}  // namespace search
}  // namespace query
}  // namespace backend
}  // namespace emulator
}  // namespace spanner
}  // namespace google
