//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "frontend/collections/operation_manager.h"

#include <algorithm>
#include <cstdint>
#include <limits>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include "absl/status/statusor.h"
#include "absl/strings/numbers.h"
#include "absl/strings/match.h"
#include "absl/strings/str_cat.h"
#include "absl/synchronization/mutex.h"
#include "common/errors.h"
#include "frontend/common/uris.h"

namespace google {
namespace spanner {
namespace emulator {
namespace frontend {

const char OperationManager::kAutoGeneratedId[] = "";

absl::StatusOr<std::shared_ptr<Operation>> OperationManager::CreateOperation(
    const std::string& resource_uri, const std::string& operation_id) {
  absl::MutexLock lock(mu_);

  // Generate an operation id if the user did not specify one. Restored
  // operations may already occupy an auto-generated ID, so advance past them.
  std::string operation_uri;
  if (operation_id.empty()) {
    if (next_operation_id_ == std::numeric_limits<int64_t>::max()) {
      return absl::OutOfRangeError(
          "System-generated operation IDs are exhausted");
    }
    do {
      operation_uri = MakeOperationUri(
          resource_uri, absl::StrCat("_auto", next_operation_id_++));
      if (next_operation_id_ == std::numeric_limits<int64_t>::max() &&
          operations_map_.contains(operation_uri)) {
        return absl::OutOfRangeError(
            "System-generated operation IDs are exhausted");
      }
    } while (operations_map_.contains(operation_uri));
  } else {
    operation_uri = MakeOperationUri(resource_uri, operation_id);
    if (operations_map_.contains(operation_uri)) {
      return error::OperationAlreadyExists(operation_uri);
    }
  }

  // Finally, create the operation.
  std::shared_ptr<Operation> operation =
      std::make_shared<Operation>(operation_uri);
  operations_map_[operation_uri] = operation;

  return operation;
}

absl::StatusOr<std::shared_ptr<Operation>>
OperationManager::RestoreOperation(
    const google::longrunning::Operation& operation_proto) {
  if (operation_proto.name().empty() || !operation_proto.done()) {
    return absl::InvalidArgumentError(
        "Restored operation must have a name and be terminal");
  }

  std::string resource_uri;
  absl::string_view operation_id;
  absl::Status parse_status =
      ParseOperationUri(operation_proto.name(), &resource_uri, &operation_id);
  if (!parse_status.ok()) {
    return parse_status;
  }
  if (MakeOperationUri(resource_uri, operation_id) != operation_proto.name()) {
    return absl::InvalidArgumentError(
        absl::StrCat("Invalid restored operation name: ",
                     operation_proto.name()));
  }

  absl::MutexLock lock(mu_);
  if (operations_map_.contains(operation_proto.name())) {
    return error::OperationAlreadyExists(operation_proto.name());
  }

  if (absl::StartsWith(operation_id, "_auto")) {
    int64_t restored_id = 0;
    if (absl::SimpleAtoi(operation_id.substr(5), &restored_id) &&
        restored_id >= 0) {
      if (restored_id == std::numeric_limits<int64_t>::max()) {
        return absl::OutOfRangeError(
            "Restored operation ID exceeds the supported range");
      }
      next_operation_id_ =
          std::max(next_operation_id_, restored_id + int64_t{1});
    }
  }

  auto operation = std::make_shared<Operation>(operation_proto);
  operations_map_.emplace(operation_proto.name(), operation);
  return operation;
}

absl::StatusOr<std::shared_ptr<Operation>> OperationManager::GetOperation(
    const std::string& operation_uri) {
  absl::MutexLock lock(mu_);

  auto itr = operations_map_.find(operation_uri);
  if (itr == operations_map_.end()) {
    return error::OperationNotFound(operation_uri);
  }
  return itr->second;
}

absl::Status OperationManager::DeleteOperation(
    const std::string& operation_uri) {
  absl::MutexLock lock(mu_);
  operations_map_.erase(operation_uri);
  return absl::OkStatus();
}

absl::StatusOr<std::vector<std::shared_ptr<Operation>>>
OperationManager::ListOperations(const std::string& resource_uri) {
  absl::MutexLock lock(mu_);
  std::vector<std::shared_ptr<Operation>> operations;
  std::string prefix = resource_uri;
  if (!absl::EndsWith(prefix, "/")) {
    prefix.push_back('/');
  }
  auto itr = operations_map_.lower_bound(prefix);
  while (itr != operations_map_.end()) {
    if (!absl::StartsWith(itr->first, prefix)) {
      break;
    }
    operations.push_back(itr->second);
    ++itr;
  }

  return operations;
}

}  // namespace frontend
}  // namespace emulator
}  // namespace spanner
}  // namespace google
