//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#include "frontend/collections/operation_manager.h"

#include <string>
#include <limits>

#include "absl/strings/match.h"
#include "frontend/entities/operation.h"
#include "gmock/gmock.h"
#include "googlesql/base/testing/status_matchers.h"
#include "gtest/gtest.h"
#include "tests/common/proto_matchers.h"

namespace google {
namespace spanner {
namespace emulator {
namespace frontend {

class OperationManagerTest : public testing::Test {
 protected:
  OperationManager* manager() { return &manager_; }

 private:
  OperationManager manager_;
};

TEST_F(OperationManagerTest, CreatesNewOperationWithUserSpecifiedID) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> operation,
      manager()->CreateOperation("projects/123/instances/456", "789"));
  google::longrunning::Operation operation_pb;
  operation->ToProto(&operation_pb);
  EXPECT_EQ("projects/123/instances/456/operations/789", operation_pb.name());
}

TEST_F(OperationManagerTest, CreatesNewOperationWithSystemGeneratedId) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> operation,
      manager()->CreateOperation("projects/123/instances/456", ""));
  google::longrunning::Operation operation_pb;
  operation->ToProto(&operation_pb);
  EXPECT_TRUE(absl::StartsWith(operation_pb.name(),
                               "projects/123/instances/456/operations/_auto"));
}

TEST_F(OperationManagerTest, SystemGeneratedIdSkipsRestoredOperation) {
  const std::string resource = "projects/123/instances/456/backups/backup";
  GOOGLESQL_ASSERT_OK(manager()->CreateOperation(resource, "_auto0"));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> operation,
      manager()->CreateOperation(resource, OperationManager::kAutoGeneratedId));
  google::longrunning::Operation operation_pb;
  operation->ToProto(&operation_pb);
  EXPECT_EQ(resource + "/operations/_auto1", operation_pb.name());
}

TEST_F(OperationManagerTest, RestoresTerminalOperationAndAdvancesGeneratedId) {
  google::longrunning::Operation restored;
  restored.set_name(
      "projects/123/instances/456/backups/backup/operations/_auto41");
  restored.set_done(true);
  restored.mutable_error()->set_code(10);
  restored.mutable_error()->set_message("restored error");

  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> operation,
      manager()->RestoreOperation(restored));
  google::longrunning::Operation actual;
  operation->ToProto(&actual);
  EXPECT_THAT(actual, test::EqualsProto(restored));

  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> generated,
      manager()->CreateOperation("projects/123/instances/456",
                                 OperationManager::kAutoGeneratedId));
  generated->ToProto(&actual);
  EXPECT_EQ(actual.name(),
            "projects/123/instances/456/operations/_auto42");

  EXPECT_THAT(manager()->RestoreOperation(restored),
              googlesql_base::testing::StatusIs(
                  absl::StatusCode::kAlreadyExists));
}

TEST_F(OperationManagerTest, RejectsGeneratedOperationIdExhaustion) {
  google::longrunning::Operation restored;
  restored.set_name(absl::StrCat(
      "projects/123/instances/456/operations/_auto",
      std::numeric_limits<int64_t>::max() - 1));
  restored.set_done(true);
  GOOGLESQL_ASSERT_OK(manager()->RestoreOperation(restored));

  EXPECT_THAT(
      manager()->CreateOperation("projects/123/instances/456",
                                 OperationManager::kAutoGeneratedId),
      googlesql_base::testing::StatusIs(absl::StatusCode::kOutOfRange));

  restored.set_name(absl::StrCat(
      "projects/123/instances/456/operations/_auto",
      std::numeric_limits<int64_t>::max()));
  EXPECT_THAT(manager()->RestoreOperation(restored),
              googlesql_base::testing::StatusIs(
                  absl::StatusCode::kOutOfRange));
}

TEST_F(OperationManagerTest, FailsToCreateOperationWithExistingURI) {
  GOOGLESQL_ASSERT_OK(
      manager()->CreateOperation("projects/123/instances/456", "789"));
  EXPECT_THAT(
      manager()->CreateOperation("projects/123/instances/456", "789"),
      googlesql_base::testing::StatusIs(absl::StatusCode::kAlreadyExists));
}

TEST_F(OperationManagerTest, GetExistingOperation) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> expected,
      manager()->CreateOperation("projects/123/instances/456", "789"));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> actual,
      manager()->GetOperation("projects/123/instances/456/operations/789"));
  EXPECT_EQ(expected, actual);
}

TEST_F(OperationManagerTest, CannotGetNonExistingOperation) {
  EXPECT_THAT(
      manager()->GetOperation("projects/123/instances/456/operations/789"),
      googlesql_base::testing::StatusIs(absl::StatusCode::kNotFound));
}

TEST_F(OperationManagerTest, DeletesAnExistingOperation) {
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> expected,
      manager()->CreateOperation("projects/123/instances/456", "789"));
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::shared_ptr<Operation> actual,
      manager()->GetOperation("projects/123/instances/456/operations/789"));
  EXPECT_EQ(expected, actual);

  GOOGLESQL_ASSERT_OK(
      manager()->DeleteOperation("projects/123/instances/456/operations/789"));
  EXPECT_THAT(
      manager()->GetOperation("projects/123/instances/456/operations/789"),
      googlesql_base::testing::StatusIs(absl::StatusCode::kNotFound));
}

TEST_F(OperationManagerTest, DeletesANonExistingOperation) {
  GOOGLESQL_ASSERT_OK(
      manager()->DeleteOperation("projects/123/instances/456/operations/789"));
}

TEST_F(OperationManagerTest, ListsOperations) {
  // Create a set of operations.
  std::string instance_uri = "projects/test-project/instances/test-instance";
  const int kNumOperations = 5;
  for (int i = 0; i < kNumOperations; ++i) {
    GOOGLESQL_ASSERT_OK(
        manager()->CreateOperation(instance_uri, absl::StrCat(i)));
  }

  // Expect that they are returned in order.
  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::vector<std::shared_ptr<Operation>> operations,
      manager()->ListOperations(instance_uri));
  EXPECT_EQ(kNumOperations, operations.size());
  for (int i = 0; i < kNumOperations; ++i) {
    google::longrunning::Operation operation_pb;
    operations[i]->ToProto(&operation_pb);
    EXPECT_EQ(absl::StrCat(instance_uri, "/operations/", i),
              operation_pb.name());
  }
}

TEST_F(OperationManagerTest, ListsOperationsWithSimilarInstanceURI) {
  const std::string kInstanceURIa =
      "projects/test-project/instances/test-instance";
  const std::string kInstanceURIb =
      "projects/test-project/instances/test-instance-a";
  GOOGLESQL_ASSERT_OK(manager()->CreateOperation(kInstanceURIa, "1"));
  GOOGLESQL_ASSERT_OK(manager()->CreateOperation(kInstanceURIb, "1"));

  GOOGLESQL_ASSERT_OK_AND_ASSIGN(
      std::vector<std::shared_ptr<Operation>> operations,
      manager()->ListOperations(kInstanceURIa));
  EXPECT_EQ(operations.size(), 1);
  google::longrunning::Operation operation_pb;
  operations[0]->ToProto(&operation_pb);
  EXPECT_EQ("projects/test-project/instances/test-instance/operations/1",
            operation_pb.name());
}

}  // namespace frontend
}  // namespace emulator
}  // namespace spanner
}  // namespace google
